### PR TITLE
Fix for some potential crashing issues and a bit of cleanup

### PR DESCRIPTION
**Pull request by SirChronus**
I added some fixes for server hard crashes.
Here's a list of changes:
- Failure to parse JSON no longer crashes server
- Removed accountList since it's not being used
- Added a payload check for hello message
- Try to avoid storing passwords and hashes in app memory

If the mongodb login part is being used, that part should be tested since I changed how users are being searched and hashes are stored. I didn't encounter any issues when testing myself.

### CODE REVIEW

**Comment by martensm** [comment]
Please merge into `develop` instead of `master`, thanks.

**Comment by nico-abram** [comment]
Skimming this, it looks good!

Thanks for this, not just your first PR but the first ever PR to this repo. 

It looks like CI is failing because of a conflict between the node version and the bcrypt version? Would you mind trying to update all deps and see if that fixes it?

**Comment by SirChronus** [comment]
CI looks good again.
bcrypt is now version 4 and seems to be working with node 12.

Just to make sure nothing breaks in the future, I added an .nvmrc file and an "engines" entry to the package.json for node v12 and up.
node >= 12.0.0 is now required to install and run everything.

I can revert the changes if that's not wanted.

**Comment by nico-abram** [comment]
Perfect. Thanks!

I honestly don't know much about node, but that sounds alright. I think I'm gonna wait until rop can check that the server is running using node 12 before merging though, my apologies.

**Pull request merged**
